# Generated by Django 3.2.13 on 2023-09-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptatiana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escola', models.CharField(max_length=100)),
                ('classificacao', models.CharField(choices=[('B', 'Básico'), ('M', 'Intermediário'), ('F', 'Fluente')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='habilidades',
            name='classificacao_habilidade',
            field=models.CharField(choices=[('T', 'Técnica'), ('C', 'Comportamental')], max_length=1),
        ),
    ]
